modLoader="javafml"
loaderVersion="[32,)"
logoFile="BiomeBorderViewerLogo.png"
[[mods]]
	modId="biomeborderviewer"
	version="1.16.1-5.0.0.0"
	displayName="Biome Border Viewer"
	updateJSONURL="https://raw.githubusercontent.com/mrp-v2/ModUpdateFiles/master/BiomeBorderViewer.json"
	issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/biome-border-viewer/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/biome-border-viewer"
	authors="mrp_v2"
	description='''Visualizes the borders of biomes.'''
[[dependencies.biomeborderviewer]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.biomeborderviewer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="CLIENT"
